service: aws-node-project

frameworkVersion: '2 || 3'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello


plugins:
  - serverless-finch


custom:
  client:
    bucketName: portalcdtusuario
    distributionFolder: client/dist